name: Build LineageOS22.2 alioth Kernel and Create Release

on:
  workflow_dispatch:
  
env:
  REPO_URL: https://github.com/LeeHe-gif/android_kernel_xiaomi_sm8250_LineageOS
  REPO_BRANCH: lineage-22.2
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install basic dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl build-essential \
            libncurses-dev bison bc flex libssl-dev \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            libelf-dev rsync kmod git cpio wget zip \
            unzip python3 python-is-python3 make xz-utils python3-pip ccache rsync

      - name: Clone kernel source and setup KernelSU
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH kernel_source
          git clone https://github.com/LeeHe-gif/AnyKernel3.git
          cd AnyKernel3
          rm -rf ramdisk anykernel.sh
          wget https://github.com/LeeHe-gif/android_kernel_xiaomi_sm8250/raw/refs/heads/15.0-alioth/AnyKernel3/anykernel.sh
  
      - name: Build kernel with clang 14.0.2(clang-r445002)
        run: |
          cp build2.sh kernel_source/
          cd kernel_source
          chmod 755 build2.sh
          ./build2.sh
            
      - name: Create anykernel3 package
        run: |
          cp kernel_source/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cd AnyKernel3/
          zip -r alioth_lineageos22.2-dockerkernel.zip anykernel.sh Image.gz-dtb LICENSE META-INF tools
          if [ -f "alioth_lineageos22.2-dockerkernel.zip" ]; then
            echo "✅ anykernel3 包创建成功"
            ls -la alioth_lineageos22.2-dockerkernel.zip
            echo "刷机包大小:"
            du -h alioth_lineageos22.2-dockerkernel.zip
          else
            echo "❌ anykernel3 包创建失败"
            exit 1
          fi
        
      - name: Create out directory archive
        run: |
          cd kernel_source
          zip -r kernel_boot_directory.zip out/arch/arm64/boot
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lineageos-kernel-build-artifacts
          path: |
            AnyKernel3/alioth_lineageos22.2-dockerkernel.zip
            kernel_source/kernel_boot_directory.zip
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    # 只有在构建成功时才运行发布
    if: success()

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lineageos-kernel-build-artifacts
          path: ./artifacts

      - name: List downloaded artifacts
        run: |
          echo "当前目录结构:"
          pwd
          ls -la
          echo "Artifacts 目录结构:"
          ls -la ./artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "alioth-lineageos22.2-kernel-build"
          name: "alioth LineageOS 22.2 Kernel Build"
          body: |
            # alioth LineageOS 22.2 Kernel Build
          
            红米 K40 LineageOS 22.2 版本内核
            分支：lineage-22.2
            ## 包含文件：
            - `alioth_lineageos22.2-dockerkernel.zip` - AnyKernel3 刷机包
            - `kernel_boot_directory.zip` - 完整的编译输出目录
          
            ## 特性：
            - ✅ 完整 Docker 容器支持
            - ✅ 基于 [LineageOS 22.2](https://github.com/LeeHe-gif/android_kernel_xiaomi_sm8250_LineageOS) 内核源码
            
            ## 刷机说明
            1. 下载 `alioth_lineageos22.2-dockerkernel.zip`
            2. 通过 TWRP Recovery 刷入
            3. 重启设备
          
            **注意：** 刷机前请备份重要数据。
          draft: false
          prerelease: false
          files: |
            ./artifacts/alioth_lineageos22.2-dockerkernel.zip
            ./artifacts/kernel_boot_directory.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
